CREATE TABLE SYS_AREA (
  RECORD_ID INT NOT NULL AUTO_INCREMENT,
  AREACODE VARCHAR(15) DEFAULT NULL,
  AREANAME VARCHAR(50) DEFAULT NULL,
  FULL_AREANAME VARCHAR(255) DEFAULT NULL,
  IS_AVAILABLE INT(1) DEFAULT 1,
  PRIMARY KEY (RECORD_ID)
) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=UTF8;