INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_ZAIHZL', '灾害种类');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'GANH', '干旱');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'HONGL', '洪涝');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'TAIF', '台风');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'FENGB', '风雹');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'DIWLD', '低温冷冻');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'XUEZ', '雪灾');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'SHACB', '沙尘暴');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'DIZ', '地震');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'SHANTBT', '山体崩塌');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHZL', 'HUOP', '滑坡');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_SHENHZT', '审核状态');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHENHZT', '00', '未上报');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHENHZT', '01', '已上报');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHENHZT', '10', '一审存留');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHENHZT', '11', '一审同意');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHENHZT', '12', '一审驳回');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHENHZT', '20', '二审存留');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHENHZT', '21', '二审同意');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHENHZT', '22', '二审驳回');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHENHZT', '30', '已启动');


INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_ZHAOPPX', '照片排序');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZHAOPPX', 'ZUIXSCZQ', '最新上传在前');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZHAOPPX', 'ZUIXSCZH', '最新上传在后');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZHAOPPX', 'ZIDYPX', '自定义排序');


INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_ZAIQZT', '灾情状态');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIQZT', 'ZAIQQD', '灾情启动');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIQZT', 'ZAIQZZ', '灾情终止');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIQZT', 'JIUZZZ', '救助终止');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_YUADJ', '预案等级');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('YUADJ', 'HONGS', '红色');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('YUADJ', 'CHENGS', '橙色');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('YUADJ', 'HUANGS', '黄色');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('YUADJ', 'LANS', '蓝色');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('YUADJ', 'QIT', '其它');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_ZAIHDJ', '灾害等级');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHDJ', 'YIJ', '一级');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHDJ', 'ERJ', '二级');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHDJ', 'SANJ', '三级');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHDJ', 'SIJ', '四级');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZAIHDJ', 'QIT', '其它');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_JIATLX', '家庭类型');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIATLX', 'DIB', '低保');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIATLX', 'WUB', '五保');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIATLX', 'YOUF', '优抚');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIATLX', 'QIT', '其它');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_JIANZJG', '建造结构');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIANZJG', 'MUF', '木房');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIANZJG', 'ZHUL', '竹楼');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIANZJG', 'ZHUANM', '砖木');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIANZJG', 'ZHUANH', '砖混');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIANZJG', 'KUANGJ', '框架');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIANZJG', 'MUQZP', '牧区帐篷');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIANZJG', 'YAOD', '窑洞');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIANZJG', 'QIT', '其它');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_SHOUZYY', '受灾原因');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHOUZYY', 'SIW', '死亡');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHOUZYY', 'SHIZ', '失踪');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHOUZYY', 'SHANGB', '伤病');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHOUZYY', 'JIANK', '健康');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_SHIZHSWYY', '失踪或死亡原因');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHIZHSWYY', 'JIANZWDT', '建筑物倒塌');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHIZHSWYY', 'NIS', '溺水');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHIZHSWYY', 'SHIYTT', '石岩坍塌');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHIZHSWYY', 'NISLYM', '泥石流掩埋');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('SHIZHSWYY', 'LEIJ', '雷击');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_ZHUANYAZLX', '转移安置类型');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZHUANYAZLX', 'FENS', '分散');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZHUANYAZLX', 'JIZ', '集中');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('ZHUANYAZLX', 'QIT', '其它');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_LINGQLX', '领取类型');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('LINGQLX', 'YILQ', '已领取');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('LINGQLX', 'WEILQ', '未领取');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_JIUZZT', '救助状态');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIUZZT', 'CHUNH', '春荒');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('JIUZZT', 'DONGL', '冬令');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('KIND', 'KIND_MINZ', '民族');

INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('MINZ', 'HANZ', '汉族');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('MINZ', 'HUIZ', '回族');
INSERT INTO SYS_DICT(DICT_TYPE, DICT_KEY, DICT_VALUE0) VALUES ('MINZ', 'MANZ', '满族');

COMMIT;
